/* eslint-disable max-len */
const mockState = [
  0,
  6698,
  'ROOT',
  {},
  [
    [
      0,
      6698,
      'Nested/Controller/Rack/AlertingUi::Application/call',
      {},
      [
        [
          0,
          6697,
          'Middleware/Rack/Rack::Sendfile/call',
          {},
          [
            [
              0,
              6697,
              'Middleware/Rack/ActionDispatch::RemoteIp/call',
              {},
              [
                [
                  0,
                  6697,
                  'Middleware/Rack/IgnoreWhitehatTransactions::Middleware/call',
                  {},
                  [
                    [
                      1,
                      6697,
                      'Middleware/Rack/Rack::Runtime/call',
                      {},
                      [
                        [
                          1,
                          6697,
                          'Middleware/Rack/Rack::MethodOverride/call',
                          {},
                          [
                            [
                              1,
                              6697,
                              'Middleware/Rack/ActionDispatch::RequestId/call',
                              {},
                              [
                                [
                                  1,
                                  6697,
                                  'Middleware/Rack/RequestStore::Middleware/call',
                                  {},
                                  [
                                    [
                                      1,
                                      6697,
                                      'Middleware/Rack/Rails::Rack::Logger/call',
                                      {},
                                      [
                                        [
                                          1,
                                          6697,
                                          'Middleware/Rack/ActionDispatch::ShowExceptions/call',
                                          {},
                                          [
                                            [
                                              1,
                                              6697,
                                              'Middleware/Rack/ActionDispatch::DebugExceptions/call',
                                              {},
                                              [
                                                [
                                                  1,
                                                  6697,
                                                  'Middleware/Rack/ActionDispatch::Callbacks/call',
                                                  {},
                                                  [
                                                    [
                                                      1,
                                                      6697,
                                                      'Middleware/Rack/ActionDispatch::Cookies/call',
                                                      {},
                                                      [
                                                        [
                                                          1,
                                                          6697,
                                                          'Middleware/Rack/ActionDispatch::Session::CookieStore/call',
                                                          {},
                                                          [
                                                            [
                                                              1,
                                                              6697,
                                                              'Middleware/Rack/ActionDispatch::Flash/call',
                                                              {},
                                                              [
                                                                [
                                                                  1,
                                                                  6697,
                                                                  'Middleware/Rack/ActionDispatch::ParamsParser/call',
                                                                  {},
                                                                  [
                                                                    [
                                                                      1,
                                                                      6697,
                                                                      'Middleware/Rack/Rack::Head/call',
                                                                      {},
                                                                      [
                                                                        [
                                                                          1,
                                                                          6697,
                                                                          'Middleware/Rack/Rack::ConditionalGet/call',
                                                                          {},
                                                                          [
                                                                            [
                                                                              1,
                                                                              6697,
                                                                              'Middleware/Rack/Rack::ETag/call',
                                                                              {},
                                                                              [
                                                                                [
                                                                                  1,
                                                                                  6697,
                                                                                  'Middleware/Rack/Rack::Attack/call',
                                                                                  {},
                                                                                  [
                                                                                    [
                                                                                      1,
                                                                                      6697,
                                                                                      'Middleware/Rack/NewRelic::Rack::BrowserMonitoring/call',
                                                                                      {},
                                                                                      [
                                                                                        [
                                                                                          1,
                                                                                          6697,
                                                                                          'Middleware/Rack/NewRelic::Rack::AgentHooks/call',
                                                                                          {},
                                                                                          [
                                                                                            [
                                                                                              1,
                                                                                              6697,
                                                                                              'Middleware/Rack/ActionDispatch::Routing::RouteSet/call',
                                                                                              {},
                                                                                              [
                                                                                                [
                                                                                                  2,
                                                                                                  6697,
                                                                                                  'Nested/Controller/incidents/acknowledge_from_external_url',
                                                                                                  {},
                                                                                                  [
                                                                                                    [
                                                                                                      70,
                                                                                                      379,
                                                                                                      'External/service-a.example.com/Net::HTTP/GET',
                                                                                                      {
                                                                                                        uri: 'http://service-a.example.com/authorization/v1/accounts/x/principal/y',
                                                                                                      },
                                                                                                      [],
                                                                                                    ],
                                                                                                    [
                                                                                                      380,
                                                                                                      388,
                                                                                                      'External/service-b.example.com/Net::HTTP/POST',
                                                                                                      {
                                                                                                        uri: 'http://service-b.example.com/alert/v1/api',
                                                                                                      },
                                                                                                      [],
                                                                                                    ],
                                                                                                    [
                                                                                                      388,
                                                                                                      6696,
                                                                                                      'External/service-b.example.com/Net::HTTP/POST',
                                                                                                      {
                                                                                                        uri: 'http://service-b.example.com/alert/v1/api',
                                                                                                      },
                                                                                                      [],
                                                                                                    ],
                                                                                                  ],
                                                                                                ],
                                                                                              ],
                                                                                            ],
                                                                                          ],
                                                                                        ],
                                                                                      ],
                                                                                    ],
                                                                                  ],
                                                                                ],
                                                                              ],
                                                                            ],
                                                                          ],
                                                                        ],
                                                                      ],
                                                                    ],
                                                                  ],
                                                                ],
                                                              ],
                                                            ],
                                                          ],
                                                        ],
                                                      ],
                                                    ],
                                                  ],
                                                ],
                                              ],
                                            ],
                                          ],
                                        ],
                                      ],
                                    ],
                                  ],
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                    ],
                  ],
                ],
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];
/* eslint-enable max-len */

export default mockState;
